### ISSUE TITLE
yt hub and demo websites are not available

### ISSUE THREAD

**Issue by migueldvb** [yt-project/website#80]
The yt hub and demo websites that are referenced in several places from the documentation are currently disabled.

https://demo.use.yt/
http://hub.yt-project.org/

**Comment by matthewturk** [comment]
@Xarthisius thoughts?

**Comment by Xarthisius** [comment]
I redirected `demo.use.yt` to https://hub.yt/#rafts. `http://hub.yt-project.org/` in yt's changelog from ages ago. There's no point in updating it.
