### ISSUE TITLE
webchat interface not working

### ISSUE THREAD

**Issue by migueldvb** [yt-project/website#81]
The web chat interface for the freenode channel does not show up in [this page](https://yt-project.org/irc.html) using Firefox. This file is not included in the git repository but looking at the source it seems that it should be working fine except that the browser may not be allowed to render the webpage inside an <iframe>.
```
<iframe src="http://webchat.freenode.net?channels=yt&uio=d4" width="100%" height="90%"></iframe>
```
This is working for me locally and the HTTP headers returned from `https://webchat.freenode.net` actually allow loading the page in a frame from other sites, so it seems to be an issue with the Apache configuration for the yt website.

**Comment by jzuhone** [comment]
@migueldvb others should comment, but I am pretty sure we are not using that anymore in favor of Slack. Which means we should get rid of the link.

**Comment by migueldvb** [comment]
Sure, that sounds reasonable. The channel looks pretty deserted although there are still some occasional guests.

**Comment by matthewturk** [comment]
I think we should probably eliminate it.
