### ISSUE TITLE
Several links on "Extension" web page are broken

### ISSUE THREAD

**Issue by bwoshea** [yt-project/website#88]
Looking at https://yt-project.org/extensions.html , there are several links that are broken:

1. The link for YTini ( http://www.ytini.com/), when clicked, leads to http://virdir.ncsa.illinois.edu/ , which is a very basic "you've landed in the wrong place" web page.
2. The "yt interaction" and ViewYT links are for bitbucket repositories that do not appear to exist any more, and throw 404 errors.

All other packages seem to work, though!

**Comment by chrishavlin** [comment]
http://www.ytini.com/ is loading as expected now, "yt interaction" and ViewYT  links still need updating
